### ISSUE TITLE
Integration error

### ISSUE THREAD

**Issue by vivekFAGH** [zyramedia/cordova-plugin-stripe#13]
I am trying to integrate this plugin in an Oracle MAF application and see errors like:

\src\com\zyramedia\cordova\stripe\CordovaStripe.java:12: error: package com.stripe.android does not exist
[05:22:05 PM] import com.stripe.android.TokenCallback;

[05:22:05 PM] \deploy\Android1\src\com\zyramedia\cordova\stripe\CordovaStripe.java:13: error: package com.stripe.android does not exist
[05:22:05 PM] import com.stripe.android.Stripe;

[05:22:05 PM] \deploy\Android1\src\com\zyramedia\cordova\stripe\CordovaStripe.java:14: error: package com.stripe.android.model does not exist
[05:22:05 PM] import com.stripe.android.model.BankAccount;

<many more....>

Is the plugin expecting any additional configuration thats not yet documented?

**Comment by ihadeed** [comment]
What version of Cordova Android are you using? What operating system?

I'll try to reproduce this on my end.

Also, try to re-install the plugin and/or the platform.

**Comment by vivekFAGH** [comment]
Cordova 4.x. Using this on oracle MAF on windows to build an android app. I am not suing android studio, hence the gradle file included in the plugin is not used.

**Comment by ihadeed** [comment]
Everything should be installed automatically for you when you run the `cordova` commands. There is no need to use Android Studio.

My guess here is that your Cordova version outdated. The latest Cordova version is `6.5.0`, and the latest Cordova Android Platform version is `6.1.0` I think. 

Run the following commands:
```
npm i -g cordova@latest

// in your project root directory
cordova platform rm --save android
cordova platform add --save android@latest
```
