### ISSUE TITLE
Add "browser" platform support

### ISSUE THREAD

**Issue by klirix** [zyramedia/cordova-plugin-stripe#2]
AFAIK there is stripe.js, that would help a great deal when writing electron apps \ debugging in browser.
I can create a pull request if needed?

**Comment by ihadeed** [comment]
Sure a PR would be nice, thanks.

The browser support should only provide a wrapper for `stripe.js`. The actual `stripe.js` script file should be included directly from `https://js.stripe.com/v2/` as instructed in their docs: https://stripe.com/docs/stripe.js#including-stripejs

**Comment by klirix** [comment]
@ #5
