### ISSUE TITLE
Add Stripe client-side validate features

### ISSUE THREAD

**Issue by fxlemire** [zyramedia/cordova-plugin-stripe#4]
https://stripe.com/docs/stripe.js#card-validation-helpers

* validateCardNumber
* validateExpiry
* validateCVC
* etc.

**Comment by ihadeed** [comment]
Hey @fxlemire ,

I will add these methods for the next release.

**Comment by fxlemire** [comment]
Awesome, thanks!

**Comment by ihadeed** [comment]
The validation methods are now available in version `1.3.0` of this plugin.
